### ISSUE TITLE
Windows Event Log not created

### ISSUE THREAD

**Issue by stesch79** [Sysinternals/SysmonForLinux#113]
**Describe the bug**
We observed on approx 1% of the installation that the Sysmon event log was not created after Sysmon was "succesfully" installed

**To Reproduce**
Install Sysmon via command line on SYSTEM context (but not always reproducable)

**Sysmon version**
14.14 and lower

**Distro/kernel version**
n/a

**Sysmon configuration**
n/a

**Logs**
n/a

**Expected behavior**
Sysmon Event Log created after installation

**Additional context**
n/a

**Comment by MarioHewardt** [comment]
Hi,

Please specify which distro/kernel version you are experiencing this on. Additionally, please specify the -t switch when starting sysmon (e.g., sudo sysmon **-t** -t <config>) and attach syslog to this issue.

**Comment by stesch79** [comment]
Hi Mario

Thanks for your follow-up. You can close the issue as we are using Windows OS and not Linux OS.

Didn’t realize that Github is only for Linux support.

Kind regards,
Stephan

**Comment by MarioHewardt** [comment]
No worries. If you want to report issues for the Windows Sysinternals tools, you can report it here - syssite@microsoft.com
