### ISSUE TITLE
Installing SysmonForLinux from Repository is failing

### ISSUE THREAD

**Issue by v4lt0n** [Sysinternals/SysmonForLinux#123]
Installing SysmonForLinux from Repository is failing

journalctl -xe
Apr 26 13:49:57 intel sysmon[395239]: Using libxml2. libxml2 is Copyright (C) 1998-2012 Daniel Veilla>
Apr 26 13:49:57 intel sysmon[395239]: Loading configuration file with schema version 4.22
Apr 26 13:49:57 intel sysmon[395239]: Sysmon schema version: 4.81
Apr 26 13:49:57 intel sysmon[395239]: Configuration file validated.
Apr 26 13:49:57 intel sysmon[395284]: Found Kernel version: 5.15
Apr 26 13:49:57 intel sysmon[395284]: Using EBPF object: .//sysmonEBPFkern5.6-_core.o
Apr 26 13:49:57 intel sysmon[395284]: libbpf: Failed to bump RLIMIT_MEMLOCK (err = -1), you might nee>
Apr 26 13:49:57 intel sysmon[395284]: libbpf: Error in bpf_object__probe_loading():Operation not perm>
Apr 26 13:49:57 intel sysmon[395284]: libbpf: failed to load object './/sysmonEBPFkern5.6-_core.o'
Apr 26 13:49:57 intel sysmon[395284]: ERROR: failed to load prog: 'Operation not permitted'
Apr 26 13:49:57 intel sysmon[395239]: Telemetry failed to start: eBPF object could not be loaded
Apr 26 13:49:57 intel systemd[1]: sysmon.service: Control process exited, code=exited, status=12/n/a
-- Subject: Unit process exited
OS ubuntu 22

**Comment by v4lt0n** [comment]
Hi, 
Im running this as root

**Comment by MarioHewardt** [comment]
Hi - Closing this for now. Please feel free to re-open with the requested information.
