### ISSUE TITLE
Sysmon installation on RHEL 9

### ISSUE THREAD

**Issue by siuolkl** [Sysinternals/SysmonForLinux#127]
Hi Everyone,

I am facing while attempting to install Sysmon on RHEL 9.
Following the provided installation instructions, I executed the following commands:
sudo rpm --import https://packages.microsoft.com/keys/microsoft.asc
sudo wget -q -O /etc/yum.repos.d/microsoft-prod.repo https://packages.microsoft.com/config/rhel/9/prod.repo
sudo dnf install sysmonforlinux

it keeps returning this error.   

Updating Subscription Management repositories.
Last metadata expiration check: 0:00:18 ago on Tue 23 May 2023 08:31:25 PM.
No match for argument: sysmonforlinux
Error: Unable to find a match: sysmonforlinux

my rhel verion
[root@localhost opt]# cat /etc/redhat-release                                                          
Red Hat Enterprise Linux release 9.0 (Plow)

any help and advise is deeply appreciated.

**Comment by MarioHewardt** [comment]
Hi, thanks for reporting this. Can you try again using the following instructions? 

```
sudo rpm --import https://packages.microsoft.com/keys/microsoft.asc
sudo wget -q -O /etc/yum.repos.d/microsoft-prod.repo https://packages.microsoft.com/config/rhel/9.0/prod.repo
sudo dnf install sysmonforlinux

```

**Comment by siuolkl** [comment]
Hi ,

ok noted.
the instructions are working now .
but when tried to verify the sysmon events its not showing up at var/log/syslog
![image](https://github.com/Sysinternals/SysmonForLinux/assets/96816514/b15764be-f28c-4492-8914-14b88ffd8310)
I tried list /var/log directory do see any syslog files.
![image](https://github.com/Sysinternals/SysmonForLinux/assets/96816514/9a51dd24-06d1-4e32-9cf3-b424671b6147)

**Comment by siuolkl** [comment]
Hi,

its working now.
thanks
