### ISSUE TITLE
Sysmon service keeps failing after a few seconds.

### ISSUE THREAD

**Issue by bchris21** [Sysinternals/SysmonForLinux#143]
Sysmon service fails after ~5 seconds.

**Sysmon version**
- sysmonforlinux-1.3.0-0 
- sysinternalsebpf-1.3.0-0 

**Distro/kernel version**
Operating System: Red Hat Enterprise Linux 8.8 (Ootpa)  
CPE OS Name: cpe:/o:redhat:enterprise_linux:8::baseos  
Kernel: Linux 4.18.0-477.21.1.el8_8.x86_64  
Architecture: x86-64  

**Sysmon configuration**
[https://github.com/microsoft/MSTIC-Sysmon/blob/main/linux/configs/main.xml](url)

**Logs**
See attached
[journalctl.txt](https://github.com/Sysinternals/SysmonForLinux/files/12814249/journalctl.txt)
[status.txt](https://github.com/Sysinternals/SysmonForLinux/files/12814252/status.txt)
[kernel.txt](https://github.com/Sysinternals/SysmonForLinux/files/12814253/kernel.txt)

**Comment by MarioHewardt** [comment]
Hi - Can you provide some more details around "Sysmon service fails"? Does it error out, stop logging? Also, can you link the logs. I can't seem to find the attachment.

**Comment by bchris21** [comment]
> Hi - Can you provide some more details around "Sysmon service fails"? Does it error out, stop logging? Also, can you link the logs. I can't seem to find the attachment.

Sorry @MarioHewardt, I forgot to attach the log files. Hope it now helps.

**Comment by MarioHewardt** [comment]
Thanks for the logs. Cursory glance (I can't repro and do not have the core dump) it seems its a seg fault in libcrypto.so.1.1.1. Due to another issue, I've bumped up the version of OpenSSL we use to 3.x. Can you try the latest Sysmon package 1.3.1 and let me know if that works?

**Comment by bchris21** [comment]
Works ok now. Thank you very much for your support!
