### ISSUE TITLE
Sysmon service fails after a while

### ISSUE THREAD

**Issue by trombomart** [Sysinternals/SysmonForLinux#150]
**Describe the bug**
When the Sysmon service is started (systemctl start sysmon), the service fails after some time. The duration is not the same for every run. One time the service fails within a couple of seconds and the other time it fails after two minutes. Also, the Sysmon service only fails for about half of our servers. The other half is working fine.

**To Reproduce**
Unknown

**Sysmon version**
v1.3.1

**Distro/kernel version**
Operating System: Red Hat Enterprise Linux 8.8 (Ootpa)
CPE OS Name: cpe:/o:redhat:enterprise_linux:8::baseos
Kernel: Linux 4.18.0-477.10.1.el8_8.x86_64
Architecture: x86-64

**Sysmon configuration**
[config.txt](https://github.com/Sysinternals/SysmonForLinux/files/12857662/config.txt)

**Logs**
[status.txt](https://github.com/Sysinternals/SysmonForLinux/files/12857678/status.txt)
[journalctl.txt](https://github.com/Sysinternals/SysmonForLinux/files/12857701/journalctl.txt) (reverse chronological order)

**Expected behavior**
The Sysmon service runs without failing after a short amount of time

**Additional context**
We also notice a memory leak, maybe this has something to do with the problem.

**Comment by ITSecOps-404** [comment]
I have the same / similar issue on Ubutnu server:
VM on HyperV
Distributor ID:  Ubuntu
Description:      Ubuntu 22.04.3 LTS
Release:            22.04
Codename:       jammy
Kernel:              5.15.0-88-generic

Sysmon version:
v1.3.1 

After install it runs for a bit then just stops, no specifc time interval.
If a system is under load and I do a fresh install of sysmon it will not start at all.

In my case it does not start again after stopping.
