### ISSUE TITLE
Provide a GUI.

### ISSUE THREAD

**Issue by RokeJulianLockhart** [Sysinternals/SysmonForLinux#158]
**Describe the bug**

https://learn.microsoft.com/en-us/sysinternals/downloads/sysmon is a gui tool. This is a TUI. Why not create it as a GUI?

**To Reproduce**

1.	Download,
2.	Compile, and
3.	Invoke https://github.com/Sysinternals/SysmonForLinux.git.

**Sysmon version**

https://github.com/Sysinternals/SysmonForLinux.git

**Distro/kernel version**

All.

**Sysmon configuration**

Default.

**Expected behavior**

SysMon should provide a GUI.

**Additional context**

https://github.com/Sysinternals/ProcMon-for-Linux/issues/102#issue-2068898730

**Comment by MarioHewardt** [comment]
Hi - thanks for the feedback. While we don't have any current plans on adding a GUI, I've tagged this issue with the enhancement tags so we can track it. Of course, we love and always welcome contributions from the community as well.
