### ISSUE TITLE
FreeBSD installation

### ISSUE THREAD

**Issue by nathmo** [Sysinternals/SysmonForLinux#171]
Hi,
This might be a noob question as I'm not familiar with freeBSD but I would like to install Sysmon on it.

There don't seem to be a dedicated entry in INSTALL.md but there seems to but some work around to use a .deb on freeBSD.
I don't know if this will work in that case, as there is a call to the packet manager (sudo apt-get install sysmonforlinux) which I don't see how to translate on freeBSD (unless I manage to get aptitude installed there, but I rather avoid that)

Thanks for the time to answer me :)

**Comment by MarioHewardt** [comment]
Hi, 

Unfortunately, we don't officially support FreeBSD. You could try compiling it and see if it works though keep in mind that Sysmon relies on eBPF and I'm not sure what the state of eBPF is on FreeBSD.
