### ISSUE TITLE
Missing config.xml file

### ISSUE THREAD

**Issue by ghost** [Sysinternals/SysmonForLinux#18]
Hi, I followed all the steps in this article on Ubuntu 20.04: [https://techcommunity.microsoft.com/t5/azure-sentinel/automating-the-deployment-of-sysmon-for-linux-and-azure-sentinel/ba-p/2847054](https://techcommunity.microsoft.com/t5/azure-sentinel/automating-the-deployment-of-sysmon-for-linux-and-azure-sentinel/ba-p/2847054).
When I try to execute `sudo sysmon -accepteula -i sysmonconfig.xml` I get `Error: Failed to open xml configuration: config.xml (No such file or directory)`.
Where can I find the config file or how to generate it?

Regards

**Comment by p3ko** [comment]
Hi, I have same problem. I don't know how CONFIG FILE should looks like.

**Comment by avwsolutions** [comment]
Also created an issue for this #14

**Comment by avwsolutions** [comment]
I found this helpful [example](https://gist.github.com/Cyb3rWard0g/bcf1514cc340197f0076bf1da8954077) . This mentioned in your techcommunity blog above btw.
