### ISSUE TITLE
amd cpu support

### ISSUE THREAD

**Issue by mengualp** [Sysinternals/SysmonForLinux#21]
I could not install this in AMD cpu server it say;

[root@centos]# yum install -y  sysmonforlinux
DigitalOcean Droplet Agent                                         36 kB/s | 3.3 kB     00:00    
Package sysmonforlinux-1.0.0-1.x86_64 is already installed.
Dependencies resolved.
Nothing to do.
Complete!

[root@centos]# sysmon -acceptuela -i sysmonconfig.xml

Sysmon v1.0.0 - Monitors system events
Sysinternals - www.sysinternals.com
By Mark Russinovich, Thomas Garnier and Kevin Sheldrake
Copyright (C) 2014-2021 Microsoft Corporation
Using libxml2. libxml2 is Copyright (C) 1998-2012 Daniel Veillard. All Rights Reserved.

Usage:
Install:                 sysmon -i [<configfile>]
Update configuration:    sysmon -c [<configfile>]
Print schema:            sysmon -s
Uninstall:               sysmon -u [force]
  -c   Update configuration of an installed Sysmon driver or dump the
       current configuration if no other argument is provided. Optionally
       take a configuration file.
  -i   Install service and driver. Optionally take a configuration file.
  -s   Print configuration schema definition of the specified version.
       Specify 'all' to dump all schema versions (default is latest)).
  -u   Uninstall service and driver. Adding force causes uninstall to proceed
       even when some components are not installed.

The service logs events immediately and the driver installs as a boot-start driver to capture
activity from early in the boot that the service will write to the event log when it starts.

On Linux, events are stored in the Syslog, often found at /var/log/syslog.

Use the '-? config' command for configuration file documentation. More examples are available on
the Sysinternals website.

**Specify -accepteula to automatically accept the EULA on installation.

Neither install nor uninstall requires a reboot.**

[root@centos]# cat /etc/os-release 
NAME="CentOS Linux"
VERSION="8"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="8"
PLATFORM_ID="platform:el8"
PRETTY_NAME="CentOS Linux 8"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:8"
HOME_URL="https://centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"
CENTOS_MANTISBT_PROJECT="CentOS-8"
CENTOS_MANTISBT_PROJECT_VERSION="8"
[root@centos]# cat /etc/redhat-release 
CentOS Linux release 8.3.2011

**Comment by frkn4129** [comment]
@mengualp  hello bro! can you  share  sysmonconfig.xml file  for me  ?
