### ISSUE TITLE
Build ready tarballs and releases

### ISSUE THREAD

**Issue by abenson** [Sysinternals/SysmonForLinux#30]
I'm sure its on the roadmap, but I'd like to ensure it is, first.

Build ready release tarballs will be necessary for it to be adopted into Linux distributions.  _By build ready I mean tarballs with any submodules already included._

I'm not sure what the roadmap for this project actually entails, but I am excited!

**Comment by kesheldr** [comment]
Hello. Which submodules are missing, and from which repo? I'm happy to make tarballs if you let me know what's currently wrong and what those tarballs need to include. Thanks.

**Comment by abenson** [comment]
Well, `sysmonCommon` for example.

**Comment by MarioHewardt** [comment]
Hi - Can you provide more details around this ask? Is it asking: For each new release make a TAR ball available that contains _all_ (incl. submodules) of the sources for Sysmon for Linux? I am not super familiar with the process of adding into Linux distribution, if you have a link to example docs I could look at that would be great.

**Comment by MarioHewardt** [comment]
Hi - Any updates on the above? Starting with 1.1, we are publishing the RPM and DEB package as part of the release.

**Comment by MarioHewardt** [comment]
Closing for now. Please reopen if the issue persists with the latest changes.
