### ISSUE TITLE
error when installing mono

### ISSUE THREAD

**Issue by maru7777** [Sysinternals/SysmonForLinux#6]
x64@Ubuntu16:~/app/SysmonForLinux/build$ sudo apt-get install monodevelop
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 monodevelop : Depends: mono-runtime-sgen but it is not going to be installed
               Depends: fsharp but it is not going to be installed
               Depends: mono-runtime (>= 3.0~) but it is not going to be installed
               Depends: libc6 (>= 2.27) but 2.23-0ubuntu11.3 is to be installed or
                        libc6.1 (>= 2.27) but it is not installable or
                        libc0.1 (>= 2.27) but it is not installable
               Depends: libfontconfig1 (>= 2.12) but 2.11.94-0ubuntu1.1 is to be installed
               Depends: libfsharp-core4.5-cil (>= 4.5) but it is not going to be installed
               Depends: libglade2.0-cil (>= 2.12.45) but it is not going to be installed
               Depends: libglib2.0-0 (>= 2.56.4) but 2.48.2-0ubuntu4.8 is to be installed
               Depends: libglib2.0-cil (>= 2.12.45) but it is not going to be installed
               Depends: libgtk2.0-cil (>= 2.12.45) but it is not going to be installed
               Depends: libmono-cairo4.0-cil (>= 3.2.1) but it is not going to be installed
               Depends: libmono-corlib4.5-cil (>= 4.0.0~alpha1) but it is not going to be installed
               Depends: libmono-microsoft-csharp4.0-cil (>= 1.0) but it is not going to be installed
               Depends: libmono-microsoft-web-infrastructure1.0-cil (>= 1.0) but it is not going to be installed
               Depends: libmono-posix4.0-cil (>= 4.0.0~alpha1) but it is not going to be installed
               Depends: libmono-system-componentmodel-composition4.0-cil (>= 3.0.6) but it is not going to be installed
               Depends: libmono-system-componentmodel-dataannotations4.0-cil (>= 4.0.0~alpha1) but it is not going to be installed
               Depends: libmono-system-configuration4.0-cil (>= 4.0.0~alpha1) but it is not going to be installed
               Depends: libmono-system-core4.0-cil (>= 4.0.0~alpha1) but it is not going to be installed
               Depends: libmono-system-data-entity4.0-cil (>= 1.0) but it is not going to be installed
               Depends: libmono-system-data-linq4.0-cil (>= 1.0) but it is not going to be installed
               Depends: libmono-system-data4.0-cil (>= 4.0.0~alpha1) but it is not going to be installed
               Depends: libmono-system-design4.0-cil (>= 1.0) but it is not going to be installed
               Depends: libmono-system-drawing4.0-cil (>= 3.0.6) but it is not going to be installed
               Depends: libmono-system-identitymodel4.0-cil (>= 4.0.0~alpha1) but it is not going to be installed
               Depends: libmono-system-io-compression4.0-cil (>= 3.2.1) but it is not going to be installed
               Depends: libmono-system-net-http4.0-cil (>= 1.0) but it is not going to be installed
               Depends: libmono-system-numerics4.0-cil (>= 1.0) but it is not going to be installed
               Depends: libmono-system-runtime-caching4.0-cil (>= 4.0.0~alpha1) but it is not going to be installed
               Depends: libmono-system-runtime-serialization4.0-cil (>= 4.0.0~alpha1) but it is not going to be installed
               Depends: libmono-system-runtime4.0-cil (>= 2.10.1) but it is not going to be installed
               Depends: libmono-system-security4.0-cil (>= 1.0) but it is not going to be installed
               Depends: libmono-system-servicemodel4.0a-cil (>= 3.2.3) but it is not going to be installed
               Depends: libmono-system-web-extensions4.0-cil (>= 2.10.3) but it is not going to be installed
               Depends: libmono-system-web-services4.0-cil (>= 1.0) but it is not going to be installed
               Depends: libmono-system-web4.0-cil (>= 2.10.3) but it is not going to be installed
               Depends: libmono-system-windows-forms4.0-cil (>= 1.0) but it is not going to be installed
               Depends: libmono-system-xaml4.0-cil (>= 1.0) but it is not going to be installed
               Depends: libmono-system-xml-linq4.0-cil (>= 3.0.6) but it is not going to be installed
               Depends: libmono-system-xml4.0-cil (>= 3.12.0) but it is not going to be installed
               Depends: libmono-system4.0-cil (>= 4.0.0~alpha1) but it is not going to be installed
               Depends: libmono-windowsbase4.0-cil (>= 3.0.6) but it is not going to be installed
               Depends: libpango-1.0-0 (>= 1.40.14) but 1.38.1-1 is to be installed
               Depends: libpangocairo-1.0-0 (>= 1.40.14) but 1.38.1-1 is to be installed
               Depends: monodoc-base (>= 3.2.1) but it is not going to be installed
               Depends: msbuild but it is not going to be installed
               Recommends: libgtk2.0-cil-dev but it is not going to be installed
               Recommends: mono-devel but it is not going to be installed
               Recommends: xamarin-gtk-theme but it is not going to be installed
E: Unable to correct problems, you have held broken packages.
x64@Ubuntu16:~/app/SysmonForLinux/build$ 

hello developer,I have no idea why i can't install monodevelop,maybe beacause i installed wine and sourceInsight before...
i try this method but it still doesn't work:
sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 3FA7E0328081BFF6A14DA29AA6A19B38D3D831EF  
echo "deb http://download.mono-project.com/repo/debian wheezy main" | sudo tee /etc/apt/sources.list.d/mono-xamarin.list  
sudo apt-get update

**Comment by juju4** [comment]
If  you are using Ubuntu 16.04 which is End Of Life, you should first switch to a more recent release.
Very unlikely to be supported.
18.04 seems the target if source build.
18.04 or 20.04 if using pre-built packages
