### ISSUE TITLE
New Packages Addressing Segfault

### ISSUE THREAD

**Issue by weslambert** [Sysinternals/SysmonForLinux#63]
I know that the source is fixed, but when will new packages addressing https://github.com/Sysinternals/SysmonForLinux/issues/9 be available? I feel like this is bug really affects being able have confidence in proper operation and adopt the usage of S4L in a consistent and scalable fashion. Thanks, as always, for the great work!  I am really looking forward to being able to have this deployed at scale.

**Comment by zCukB** [comment]
I have the same problem. Unfortunately, the bug is so critical, that we cannot deploy sysmon for linux in our company.

**Comment by MarioHewardt** [comment]
We are in the process of building the new packages and hopefully will have them out by end of week. Thanks for your patience.

**Comment by weslambert** [comment]
> We are in the process of building the new packages and hopefully will have them out by end of week. Thanks for your patience.

Thanks, @MarioHewardt! Looking forward to it!

**Comment by MarioHewardt** [comment]
Update - we are still working on the packages and we will let you know ASAP once they are available. Thanks for your patience.

**Comment by MarioHewardt** [comment]
Thank you for your patience. The new packages (1.0.2) are now available.
