### ISSUE TITLE
License conflict

### ISSUE THREAD

**Issue by fidomax** [Sysinternals/SysmonForLinux#7]
static const char RawEulaText conflicts with MIT license above:
MIT:
Permission is hereby granted, free of charge, to any person obtaining a copy of this software and associated documentation files (the ""Software""), to deal in the Software without restriction, including without limitation the rights to use, copy, modify...
EULA:
You may not\n* work around any technical limitations in the software;\n*reverse engineer, decompile or disassemble the software...

**Comment by hillu** [comment]
Just get rid of the EULA. It annoys users and serves no purpose, especially if it `sysmon -accepteula` is run from automated installation procedures or via Ansible.

**Comment by MarioHewardt** [comment]
Hi - Agreed, it does create some confusion. 

I've removed the EULA
