### ISSUE TITLE
Problems logging rules

### ISSUE THREAD

**Issue by rblader** [Sysinternals/SysmonForLinux#75]
Borrowing from examples posted in https://github.com/microsoft/MSTIC-Sysmon/blob/main/linux/configs/main.xml, I've found rule names such as:
     \<Rule name="TechniqueID=T1070.006,TechniqueName=Indicator Removal on Host: Timestomp"... > 
           \<Image condition="end with">touch\</Image>
      \</Rule>

This gets truncated in syslog at  to:
         \<Data Name="RuleName">TechniqueID=T1070.006,TechniqueName=Indi</Data>

To shorten the message I tried:
    \<Rule name="T1070.006, Timestomp" groupRelation="or">

This gets ignored entirely.  When included in the ProcessCreate section, processes associated with 'touch' are not logged at all.

Trial and error show that including or omitting "TechniqueID=" and "TechniqueName=" affect how much the field is truncated, and omitting both field names appears to prevent logging entirely.  

Is there any specific guidance on how Rule Names are parsed, limitations on length of the string, and formatting?

**Comment by MarioHewardt** [comment]
Thanks for reporting this - we will investigate.

**Comment by rblader** [comment]
Thank you!  If I can help with testing updates, please feel free to let me
know.

-Rob Blader

**Comment by MarioHewardt** [comment]
There was an issue with the rule names which I just fixed. If you want to give it a try and let me know that would be great. For now you will have to build since we haven't published a new package yet.

**Comment by rblader** [comment]
Got it, thanks

Rob Blader
