### ISSUE TITLE
SysmonUnitTest - ID: 'RuleEngine', ERROR:13

### ISSUE THREAD

**Issue by fxploit** [Sysinternals/SysmonForLinux#77]
[ HOST INFO]
OS : Ubuntu 22.04.1 LTS
Kernel : Linux 5.15.0-41-generic
Architecture : x86-64

Hello, an error occurred during the Sysmon Unit Test process.
I don't know where to look when this error occurs.
I attached the part with the log.

![image](https://user-images.githubusercontent.com/63603934/187829684-f205ba52-0ef7-497b-8268-c84ed94c7142.png)

![image](https://user-images.githubusercontent.com/63603934/187829819-6f711e05-d06f-471a-843f-985b18b66254.png)

![image](https://user-images.githubusercontent.com/63603934/187829889-7daa7a73-5f4c-4eea-979b-5569e724373a.png)

![image](https://user-images.githubusercontent.com/63603934/187829975-dfd177b9-f2c5-444f-9118-78b70a24ad7d.png)

![image](https://user-images.githubusercontent.com/63603934/187830109-c1577c4e-31a0-4293-a042-46380ccf7aa7.png)

**Comment by MarioHewardt** [comment]
@fxploit  - With the latest changes to Sysmon, I'm not able to reproduce this anymore. Could you try and let me know if it reproduces for you?

**Comment by MarioHewardt** [comment]
This should now be fixed.
