### ISSUE TITLE
Missing #include <cstdio> in networkTracker.cpp

### ISSUE THREAD

**Issue by pope-es** [Sysinternals/SysmonForLinux#8]
In Ubuntu 20.04, when building, make complains about "stderr" and "fprintf" in networkTracker.cpp.

Adding #include <cstdio> solved the issue.

**Comment by kesheldr** [comment]
I don't know why that was complaining but the #include for stdio.h has been added now so hopefully fixed. Let me know.

**Comment by MarioHewardt** [comment]
Closing for now. Please reopen if the issue persists with the latest changes.
