### ISSUE TITLE
Callinng pthread_t instead of pthread_create durig make.

### ISSUE THREAD

**Issue by alphamystic** [Sysinternals/SysmonForLinux#85]
sudo make
Consolidate compiler generated dependencies of target checkEBPFsizes
[  2%] Built target checkEBPFsizes
Consolidate compiler generated dependencies of target sysmonLogView
[ 17%] Built target sysmonLogView
Consolidate compiler generated dependencies of target sysmon
[ 18%] Building CXX object CMakeFiles/sysmon.dir/sysmonCommon/networkmiscCommon.cpp.o
/opt/tools/SysmonForLinux/sysmonCommon/networkmiscCommon.cpp: In member function ‘bool CHostNameResolver::AddAddress(const BYTE*, bool)’:
/opt/tools/SysmonForLinux/sysmonCommon/networkmiscCommon.cpp:661:20: error: ‘pthread_create’ was not declared in this scope; did you mean ‘pthread_t’?
  661 |         int tRet = pthread_create( &hThread, NULL, AddThread, (void *)context );
      |                    ^~~~~~~~~~~~~~
      |                    pthread_t
/opt/tools/SysmonForLinux/sysmonCommon/networkmiscCommon.cpp:663:13: error: ‘pthread_join’ was not declared in this scope; did you mean ‘pthread_t’?
  663 |             pthread_join( hThread, NULL );
      |             ^~~~~~~~~~~~
      |             pthread_t
/opt/tools/SysmonForLinux/sysmonCommon/networkmiscCommon.cpp: In member function ‘bool CPortNameResolver::AddPort(WORD, bool)’:
/opt/tools/SysmonForLinux/sysmonCommon/networkmiscCommon.cpp:889:20: error: ‘pthread_create’ was not declared in this scope; did you mean ‘pthread_t’?
  889 |         int tRet = pthread_create( &hThread, NULL, AddThread, (void *)context );
      |                    ^~~~~~~~~~~~~~
      |                    pthread_t
/opt/tools/SysmonForLinux/sysmonCommon/networkmiscCommon.cpp:891:13: error: ‘pthread_join’ was not declared in this scope; did you mean ‘pthread_t’?
  891 |             pthread_join( hThread, NULL );
      |             ^~~~~~~~~~~~
      |             pthread_t
make[2]: *** [CMakeFiles/sysmon.dir/build.make:372: CMakeFiles/sysmon.dir/sysmonCommon/networkmiscCommon.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:105: CMakeFiles/sysmon.dir/all] Error 2
make: *** [Makefile:91: all] Error 2

**********************************************************************
I HAD INSTALLED libEBPF before though and all was well with it.
************************************************************************

**Comment by MarioHewardt** [comment]
Hi - It looks like you don't have pthreads installed. Can you try installing it?

**Comment by MarioHewardt** [comment]
Closing for now. Feel free to reopen if you are still encountering the issue.
