### ISSUE TITLE
Installation on Ubuntu. 22.04 failed

### ISSUE THREAD

**Issue by ipcis** [Sysinternals/SysmonForLinux#86]
Followed the steps in the description:
wget -q https://packages.microsoft.com/config/ubuntu/$(lsb_release -rs)/packages-microsoft-prod.deb -O packages-microsoft-prod.deb
sudo dpkg -i packages-microsoft-prod.deb
sudo apt-get update
sudo apt-get install sysmonforlinux

E: Unable to locate package sysmonforlinux

Repo is in the source-list, had run apt update, but didn't worked.

**Comment by PwndYA** [comment]
There is no Ubuntu 22.04 Support yet. Or am I wrong?

**Comment by ipcis** [comment]
Maybe thats the issue. Thought I read something about Ubuntu 20 or higher. But I can be wrong.

**Comment by ipcis** [comment]
The installation instructions are declared "For Ubuntu 20.04 and later".

**Comment by MarioHewardt** [comment]
We don't have packages for 22.04 (yet) as the preview was released prior to 22.04 releasing. I'm in the process of making some fixes to the eBPF verifier failing to load on some distros and once that is done, we will publish new packages. In the meantime, if possible, you can always build it (or try installing the 20.04 package on 22.04).

**Comment by PwndYA** [comment]
Hey Mario, i tried  installing it on 22.04 but always get stucked. but never mind, i will wait for your guys release. take your time :)

**Comment by MarioHewardt** [comment]
Closing as I've pushed a fix that should resolve the issue. If you encounter it again, please reopen. Please note that you will have to build Sysmon until we get new packages out.
