### ISSUE TITLE
Cannot allocate memory on sysmon.service start

### ISSUE THREAD

**Issue by madsenjack** [Sysinternals/SysmonForLinux#93]
Hello, I have been recently trying to install sysmon on a Ubuntu 22.04 server, and after following the installation guide outlined in this project I am running into a "failed to mmap perf buffer on cpu #3: cannot allocate memory" error output on sysmon service start.

I have included a screenshot of the error output of "systemctl status sysmon.service" (I hope you can see the screenshot) 

Any help or guidance with this error would be appreciated! Thank you!

![Screenshot from 2023-01-24 08-18-20](https://user-images.githubusercontent.com/99513198/214306270-a263b0cc-a12c-4fc3-a26f-1091c862140a.png)

**Comment by MarioHewardt** [comment]
Hi - thanks for reporting this, I'll add it to the backlog. I'm working on some enhancements at the moment and as part of those I've ran it on 22.04 without problems. I'll update once those enhancements are done.

**Comment by madsenjack** [comment]
Thank you very much, I appreciate your help!

**Comment by madsenjack** [comment]
Error resolved after full system reboot and update.
